### ISSUE TITLE
关于DeadLetterMessageListener 疑问

### ISSUE THREAD

**Issue by wfm0105** [vvsuperman/coolmq#1]
看了下代码，请问能否带上消费模块的例子，还有一些代码没有开源出来，比如说，发邮件和 入库那块的用到的服务，本人邮箱wfm0105@16.3.com

**Comment by vvsuperman** [comment]
入库和发邮件都是消息失败了后人肉兜底的提醒手段，每家的处理方式都不一样，这块的代码实际已经不属于消息队列模块的处理范畴了。消费者模块我再补个具体点的例子吧。

**Comment by wfm0105** [comment]
支持

**Comment by vvsuperman** [comment]
咳咳，我直接关了吧，看有啥更优雅的方案
