### ISSUE TITLE
没怎么看明白事务在哪

### ISSUE THREAD

**Issue by duansheli** [vvsuperman/coolmq#6]
有没有具体的例子 比如
跨库 转账 
跨库 减库存 更新订单状态

**Comment by vvsuperman** [comment]
这种问题不应该是issue，请去问题板块提问
参考：https://segmentfault.com/a/1190000012762869
https://segmentfault.com/a/1190000011479826
rocketmq：https://www.jianshu.com/p/53324ea2df92
等等，或者是一些事务的的基础知识，cap原理等等
以及讲座：https://segmentfault.com/l/1500000012729662
