### ISSUE TITLE
貌似项目里没有一个完整的业务DEMO

### ISSUE THREAD

**Issue by killkiss** [vvsuperman/coolmq#8]
没有看到业务上MqSender注解的使用，没有业务DEMO拼命。业务上不方便测试效果。能不能后期加上

**Comment by vvsuperman** [comment]
注解的使用还未实现完成，demo不是提供了么？

**Comment by vvsuperman** [comment]
注解不可用，后续加入回查，耦合会比较深，不太方便用注解。至于demo，提供的是通用的，你需要自己实现： 业务A-> 发消息 -> 业务B
